### ISSUE TITLE
Fix instructions to include info on installing ffmpeg

### ISSUE THREAD

**Issue by chrisrytting** [andrewnc/algorithms_animated#4]
tl;dr add instructions to install ffmpeg

`pip install manim` doesn't install one of its dependencies, which is the package `ffmpeg`. I tried to install it with pip, but I needed to manually add its location to my PATH, and then it was denying me permission and when I did it with sudo, it couldn't find the command and all this craziness.

Tried `brew install ffmpeg` and didn't work either

**Comment by andrewnc** [comment]
Installing via homebrew should work

https://superuser.com/questions/624561/install-ffmpeg-on-os-x

**Comment by chrisrytting** [comment]
I don't know why `brew install ffmpeg` didn't work for me last night, but I guess you fixed it this morning by saying it should work, since I tried it again and it worked when I joint-installed it w/ mactex. Prolly user error.
